# $OpenBSD: Makefile,v 1.29 2017/11/16 23:20:39 naddy Exp $

COMMENT =	interface to Brands and Chaumian credentials

VERSION =	0.09
DISTNAME =	credlib-${VERSION}
EXTRACT_SUFX = .tgz
ALL_TARGET = generic
CATEGORIES =	security
#REVISION =	3

HOMEPAGE =	http://www.cypherspace.org/credlib/

MASTER_SITES =	${HOMEPAGE}source/

# Public domain as per private email from Adam Back
PERMIT_PACKAGE_CDROM =		Yes

NO_TEST =		Yes

.include <bsd.port.mk>
