
COMMENT    =	modular irc server

GH_ACCOUNT = 	freenode
GH_PROJECT =	ircd-seven
GH_TAGNAME =	ircd-seven-1.1.5

PKGNAME =	ircd-seven-1.1.5

CATEGORIES = 	net

MAINTAINER = 	Alex Holst <a@mongers.org>
HOMEPAGE =	https://www.freenode.net/

PERMIT_PACKAGE_CDROM =	Yes

#USE_GMAKE	=	Yes
SEPARATE_BUILD = 	flavored
CONFIGURE_STYLE = 	gnu	

.include <bsd.port.mk>
